### ISSUE TITLE
Change command on object to generate a migration instead of directly creating the tables

### ISSUE THREAD

**Issue by nielsm** [winton/acts_as_archive#1]
As currently implemented, deployments thru Capistrano are much harder as you have to manually go into the production environment & run the command.  If the command instead generated the migration, it could be deployed exactly the same as before thru cap deploy:migrations.

**Comment by winton** [comment]
Hello,

This actually is possible, but not documented. You would simply put this line in a migration of your choosing:

<pre>
ActsAsArchive.update Article, Comment
</pre>


Of course you would replace "Article, Comment" with your models. I will update the README with this information and then close this ticket out.

**Comment by look** [comment]
winton, thanks for adding the docs for this. I figured out how to do this while hacking on the code, but I thought I'd need to add this functionality.

**Comment by winton** [comment]
No problem at all. I can't think of a logical reason why we didn't deploy this using migrations, but there was a reason. We deployed a little under a year ago, so my memory fails me :)

**Comment by ramontayag** [comment]
I ran `rake db:migrate` as shown in the README but can't find any trace of these new tables. I came here and saw this, and tried it too, but it doesn't seem to work.
