### ISSUE TITLE
How do I bootstrap the test environment?

### ISSUE THREAD

**Issue by grant-olson** [winton/acts_as_archive#10]
Apologies if this is a stupid question.  I haven't tried to work with a gem before.

I'm trying to use acts_as_archive with JRuby.  I'm using mysql, but because it's jruby the adapter is jdbcdriver.

I was hoping that I could just add a condition in tables.rb, and things would work.

I downloaded, tried to run the specs, and it complained about a missing db.  I created the db, but now I don't have any tables.

If you could point me in the right direction to get the test suite going, I'd appreciate it.

**Comment by winton** [comment]
Sorry for the long wait for a reply. I have recently upgraded the gem and will be adding directions on the wiki soon.

Edit <code>fixtures/config/database.yml</code>, <code>fixtures/frameworks/rails2/database.yml</code>, and <code>fixtures/frameworks/rails3/database.yml</code>.

<pre>
cd spec
rake db:drop db:create
cd ../
spec/run
</pre>


More detailed instructions to come.
