### ISSUE TITLE
acts_as_archive breaking thinking_sphinx

### ISSUE THREAD

**Issue by alibby** [winton/acts_as_archive#25]
We added acts_as_archive to a project using thinking_sphinx. When we did so, 
thinking_sphinx lost the ability to determine the list of models that have sphinx indexes.

 We're still trying to nail down if the issue is here or in thinking_sphinx, but I've got a hunch
acts_as_archive is making some change to the active record models it's added to which
break some conventions that thinking_sphinx is counting on.

**Comment by rymohr** [comment]
Ever determine the cause on this one?

**Comment by alibby** [comment]
I imagine this is old enough to close.
