### ISSUE TITLE
problem with the yaml in the gem?

### ISSUE THREAD

**Issue by sp7777** [winton/acts_as_archive#36]
I'm using Rails 3.1 and just put acts_as_archive into my gemfile.  Doing nothing else, I ran rake and get the following dump:  It looks as though there is some invalid yaml in the gem.  If I change my yaml parser to syck, it's ok (but syck is an old parser and should not be used).

rake --trace
rake aborted!
couldn't parse YAML at line 2 column 9
/blah/blah/ruby-1.9.2-p290/lib/ruby/1.9.1/psych.rb:148:in `parse'
/blah/blah/ruby-1.9.2-p290/lib/ruby/1.9.1/psych.rb:148:in`parse_stream'
/blah/blah/ruby-1.9.2-p290/lib/ruby/1.9.1/psych.rb:119:in `parse'
/blah/blah/ruby-1.9.2-p290/lib/ruby/1.9.1/psych.rb:106:in`load'
/blah/blah/ruby-1.9.2-p290@rails3/gems/acts_as_archive-0.4.0/lib/acts_as_archive/gems.rb:66:in `block in gemset='
/blah/blah/ruby-1.9.2-p290@rails3/gems/acts_as_archive-0.4.0/lib/acts_as_archive/gems.rb:64:in`collect'
/blah/blah/ruby-1.9.2-p290@rails3/gems/acts_as_archive-0.4.0/lib/acts_as_archive/gems.rb:64:in `gemset='
/blah/blah/ruby-1.9.2-p290@rails3/gems/acts_as_archive-0.4.0/lib/acts_as_archive/gems.rb:37:in`activate'
/blah/blah/ruby-1.9.2-p290@rails3/gems/acts_as_archive-0.4.0/lib/acts_as_archive.rb:3:in `<top (required)>'
/blah/blah/ruby-1.9.2-p290@rails3/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in`require'
/blah/blah/ruby-1.9.2-p290@rails3/gems/bundler-1.0.18/lib/bundler/runtime.rb:68:in `block (2 levels) in require'
/blah/blah/ruby-1.9.2-p290@rails3/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in`each'
/blah/blah/ruby-1.9.2-p290@rails3/gems/bundler-1.0.18/lib/bundler/runtime.rb:66:in `block in require'
/blah/blah/ruby-1.9.2-p290@rails3/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in`each'
/blah/blah/ruby-1.9.2-p290@rails3/gems/bundler-1.0.18/lib/bundler/runtime.rb:55:in `require'
/blah/blah/ruby-1.9.2-p290@rails3/gems/bundler-1.0.18/lib/bundler.rb:120:in`require'

**Comment by dvdplm** [comment]
this is not fixed.
