### ISSUE TITLE
Malfunction on Windows

### ISSUE THREAD

**Issue by romansklenar** [winton/acts_as_archive#4]
Hi, I have an issue with loading server after I installed this gem with <code>gem install acts_as_archive --include-dependencies</code>

OS: Windows 7, x86
Ruby: 1.8.6
Gem: 1.3.6
Rails: 2.3.5

Here is a stack trace:

<pre>
=> Booting WEBrick
=> Rails 2.3.5 application starting on http://0.0.0.0:3000
no such file to load -- lib/acts_as_archive/base
C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require'
C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require!'
C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `each'
C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `require!'
C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:49:in `method_missing'
C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `each'
C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `method_missing'
C:/ruby/lib/ruby/gems/1.8/gems/acts_as_archive-0.2.4/lib/acts_as_archive.rb:2
C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
C:/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
C:/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:208:in `load'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in `load_gems'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in `each'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in `load_gems'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:164:in `process'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `send'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
C:/rails/todo/config/environment.rb:25
C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
C:/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require': no such file to load -- lib/acts_as_archive (MissingSourceFile)
        from C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require!'
        from C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `each'
        from C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `require!'
        from C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:49:in `method_missing'
        from C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `each'

C:/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
script/server:3
        from C:/ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `method_missing'
        from C:/ruby/lib/ruby/gems/1.8/gems/acts_as_archive-0.2.4/rails/init.rb:2:in `evaluate_init_rb'
        from C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/plugin.rb:158:in `evaluate_init_rb'
         ... 16 levels...
        from C:/ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
        from C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from C:/ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from script/server:3
</pre>

Tested on acts_as_archive >= 2.0.1, version 2.0.0 works fine.

**Comment by plagi** [comment]
Hello, I have the same issue did you manage to fix it?

<pre><code>
=> Booting WEBrick
=> Rails 2.3.5 application starting on http://0.0.0.0:3000
no such file to load -- lib/acts_as_archive/base
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require'
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require!'
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `each'
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `require!'
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:49:in `method_missing'
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `each'
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `method_missing'
C:/Ruby/lib/ruby/gems/1.8/gems/acts_as_archive-0.2.4/lib/acts_as_archive.rb:2
C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/gem_dependency.rb:208:in `load'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in `load_gems'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in `each'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:307:in `load_gems'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:164:in `process'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `send'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `run'
D:/WORK/my/CourierPlus/config/environment.rb:21
C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
C:/Ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
script/server:3
C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require': no such file to load -- lib/acts_as_archive (MissingSourceFile)
        from C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:67:in `require!'
        from C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `each'
        from C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:62:in `require!'
        from C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:49:in `method_missing'
        from C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `each'
        from C:/Ruby/lib/ruby/gems/1.8/gems/require-0.2.1/lib/require.rb:43:in `method_missing'
        from C:/Ruby/lib/ruby/gems/1.8/gems/acts_as_archive-0.2.4/rails/init.rb:2:in `evaluate_init_rb'
        from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/rails/plugin.rb:158:in `evaluate_init_rb'
         ... 16 levels...
        from C:/Ruby/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/server.rb:84
        from C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from C:/Ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from script/server:3
</code></pre>

Thanks

**Comment by romansklenar** [comment]
Not yet, I just used version 2.0.0 for now where it works.

**Comment by settu** [comment]
installed as plugin. In require.rb changed the paths as 

  lib do
    require "vendor/plugins/acts_as_archive/lib/acts_as_archive/base"
    require "vendor/plugins/acts_as_archive/lib/acts_as_archive/base/adapters/mysql"
    require "vendor/plugins/acts_as_archive/lib/acts_as_archive/base/adapters/postgresql"
    require "vendor/plugins/acts_as_archive/lib/acts_as_archive/base/destroy"
    require "vendor/plugins/acts_as_archive/lib/acts_as_archive/base/restore"
    require "vendor/plugins/acts_as_archive/lib/acts_as_archive/base/table"
    require "vendor/plugins/acts_as_archive/lib/acts_as_archive/migration"
  end

  rails_init { require 'vendor/plugins/acts_as_archive/lib/acts_as_archive' }

Now it works fine.

**Comment by winton** [comment]
This should be fixed with the new version (0.3.0). It no longer uses the require gem.
