### ISSUE TITLE
tables created but no class files

### ISSUE THREAD

**Issue by beecourt** [winton/acts_as_archive#41]
I am using rails 3.0.7 with a_a_a 0.4.1 and MySQL.
There are ":dependent => :destroy" annotations in my models.
When I run rake db:migrate new tables will be created with "deleted_at" fields, but no new class files are created. Also there are no new/renamed id fields for the altered dependencies. Shouldn't there be any?

Example:

Account model:

<pre>
class Account < ActiveRecord::Base<br>
  has_many :invoices, :dependent => :destroy
</pre>

config/acts_as_archive.yaml:

<pre>
Account:
  - class: Account::Archive
    table: archived_accounts
Invoice:
  - class: Invoice::Archive
    table: archived_invoices
</pre>

**Comment by johncant** [comment]
No, this is normal behaviour. The classes must be created dynamically somehow.
