### ISSUE TITLE
Referential integrity after primary key collisions

### ISSUE THREAD

**Issue by johncant** [winton/acts_as_archive#42]
Hi all, I've got a question about this gem:

Supposing I have these models in Rails:

``` ruby
class Foo < ActiveRecord::Base
  acts_as_archive ....
  has_one :bar, :dependent => :destroy
end

class Bar < ActiveRecord::Base
  acts_as_archive ...
  belongs_to :foo
end
```

Then I do:

``` ruby
Foo.find(6).destroy # It ends up in Foo::Archive with id 6 and Foo.find(6).bar ends up in Bar::Archive
```

Then, much later, someone creates another Foo and unluckily it has id 6 and deletes it:

``` ruby
Foo.find(6).destroy # Primary key collision
```

What happens to the referential integrity of the archive tables?

**Comment by elmatou** [comment]
Sadly this library is not supported anymore.
But because I had to dig in the code, I can tell you there is no integrity check. 
The gem assume that id are affected incrementaly (eg : with AUTO_INCREMENT in MySQL).

**Comment by johncant** [comment]
Can we assume this for any database that rails has an adapter for? For instance Postgres?

**Comment by elmatou** [comment]
I'm pretty sure we can assume it for SQL databases (including PostgreSQL), but I have no idea for non relational databases (anyhow this library has no adapter for them).

**Comment by johncant** [comment]
Cheers elmatou! Now I know that I can use in my app a version of this gem+mover+also_migrate and that I hacked to work with PostgreSQL and Rails 3.1 reversible migrations. I've submitted all of my changes. The annoying thing, we realised only after modifying acts_as_archive that it was going to be easier (in our case) to write a simpler version of acts_as_paranoid, which took an afternoon.
