### ISSUE TITLE
ActsAsArchive.update will fail if index is set a non-yet-existing column

### ISSUE THREAD

**Issue by gravis** [winton/acts_as_archive#7]
Steps to reproduce :
1. Add acts_as_archive to model Article, and create migration with <pre>ActsAsArchive.update Article</pre>
2. Add a new column to model Article in a migration, say "status"
3. Add the :index => [:status] to acts_as_archive
4. Push you work

The first migration will fail because acts_as_archive will try to create an index on :status which is not yet available. This could be prevented by testing presence of column before setting indexes, and warn if not available instead of crash the migration.
I'll see what I can do there.

**Comment by gravis** [comment]
Fixed in http://github.com/gravis/acts_as_archive/commit/d62aa1db3a2ee4f830b7f87b7c9b332e2bfaa2ac
and http://github.com/gravis/acts_as_archive/commit/5698dc48efc120153d75f1f1aae4676f71494ecc

**Comment by winton** [comment]
This should be resolved now in version 0.3.0. Also, calling <code>ActsAsArchive.update</code> is no longer necessary, it will automatically run when <code>rake db:migrate</code> is executed.
