### ISSUE TITLE
PGSQL tests fail to pass

### ISSUE THREAD

**Issue by gravis** [winton/acts_as_archive#8]
fixed in http://github.com/gravis/acts_as_archive/commit/584b737207bc4a1ce58f7ec7227207c20e43b503

**Comment by winton** [comment]
Thanks for this. I'm closing this ticket because I did not include PostgreSQL in the specs for version 0.3.0. It should work fine with it though.

If you wanted to submit a patch that includes them, I would be more than happy to add it.
