### ISSUE TITLE
Don't work in Rails 3

### ISSUE THREAD

**Issue by grimen** [winton/acts_as_archive#9]
In my model:

<pre>
class Product < ActiveRecord::Base
  acts_as_archive
end
</pre>

Error:

<pre>
ActionController::RoutingError (undefined local variable or method `acts_as_archive' for #< Class:0x000001037b1930 >):
  app/models/product.rb:1:in `<class:Product>'
  app/models/product.rb:1:in `<top (required)>'
  app/controllers/products_controller.rb:1:in `<top (required)>'
</pre>

**Comment by clemens** [comment]
Any plans on fixing this up for Rails 3 properly?

**Comment by emilford** [comment]
Also interested in a Rails 3 version.  Thanks!

**Comment by ariera** [comment]
I'm interested as well
Thanks : )

**Comment by bhavinjavia** [comment]
I'm evaluating this gem for my Rails 2.3.8 project. We plan to move to Rails 3 soon. Is there any plan to support Rails 3 within the next month or two ?

**Comment by nielsm** [comment]
Me too

**Comment by vadimt** [comment]
me three

**Comment by jacklin10** [comment]
I would be interested in rails 3 compatibility also.  At least mention if you plan on making this upgrade.  Thanks so much!

**Comment by xxx** [comment]
Hi,

I've spent the day updating my fork for Rails 3 compatability. The spec suite is fully green and hand-testing in a somewhat trivial app works fine as well, including ActsAsArchive.update

It's at http://github.com/xxx/acts_as_archive

I'll take bug reports for awhile, though I don't intend to take the gem over long-term.

This fork does _not_ support Rails 2.x, though.

**Comment by winton** [comment]
Hey guys,

You'll be happy to hear that version 0.3.0 now supports both Rails 2 and 3. I would love to get some feedback before I announce it officially.

**Comment by xxx** [comment]
Initial testing looks good here.

**Comment by winton** [comment]
Thanks Michael. Thank you for the work in your branch as well, it helped me make some hard decisions relating to the new version.

**Comment by grimen** [comment]
@winton: Awesome effort! I never thought anyone would have energy enough to spend on it so I was about to nuke it from my app. :)
